name: Builds TopCPToolkit science image

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: TopCPToolkit
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            ANALYSISBASE_TAG=25.2.38
            TOPCPTOOLKIT_TAG=2.16.1
            GIT_KEY=${{ secrets.GITLAB_TOKEN }}
          tags: sslhep/servicex_science_image_topcp:2.16.1-25.2.38
          platforms: linux/amd64,linux/arm64